<footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; ARIS Remittance 2020</div>
                            <div>
                                <!-- <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a> -->
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="<?php echo base_url(); ?>assets/js/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
        <script src="<?php echo base_url(); ?>assets/js/sweetalert.js"></script>
        <script src="<?php echo base_url(); ?>assets/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="<?php echo base_url(); ?>assets/js/scripts.js"></script>
        
        <script>
            var baseurl = "<?php echo base_url(); ?>";
        </script>
        <script src="<?php echo base_url(); ?>assets/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
        <script src="<?php echo base_url(); ?>assets/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
        <script src="<?php echo base_url(); ?>assets/demo/datatables-demo.js"></script>
        <script src="<?php echo base_url(); ?>assets/js/myjs.js"></script>
        <script src="<?php echo base_url(); ?>assets/js/salesman.js"></script>
        <script src="<?php echo base_url(); ?>assets/js/cashier.js"></script>

        <script src="<?=base_url()?>assets/js/dataTables.buttons.min.js"></script>
        <script src="<?=base_url()?>assets/js/buttons.html5.min.js"></script>
        <script src="<?=base_url()?>assets/js/jszip.min.js"></script>
        <script src="<?=base_url()?>assets/js/pdfmake.js"></script>
        <script src="<?=base_url()?>assets/js/vfs_fonts.js"></script>

        <link href="<?php echo base_url(); ?>assets/css/select2.css" rel="stylesheet" />
        <!-- <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script> -->
        <script src="<?php echo base_url(); ?>assets/js/select2.js"></script>

        <!-- jQuery UI CSS -->
        <link rel="stylesheet" href="<?php echo base_url(); ?>assets/css/jquery-ui.css">

        <!-- jQuery UI JS -->
        <script src="<?php echo base_url(); ?>assets/js/jquery-ui.min.js"></script>


        <script>
            $(document).ready(function() {
                $('#sm').select2({
                    placeholder: "Select Salesman",
                    allowClear: true
                });

                $('#sm_xt').select2({
                    placeholder: "Select Salesman",
                    allowClear: true
                });
            });
        </script>
        
        <script>

            

            // Append the Grand Total row outside DataTables processing
        
            var table = $('table#dataTableLogs').removeAttr('width').DataTable({
                //dom: 'Blfrtip', // Adds the button control panel
                dom: "<'text-right'B><'row'<'col-md-5 col-12'l><'col-md-7 col-12'f>>r<'table-responsive't><'row'<'col-md-5 col-12'i><'col-md-7 col-12'p>>",
                buttons: [
                    {
                        extend: 'copy',
                        title: 'LOGS',
                        exportOptions: {
                            columns: [0, 1, 2, 3, 4, 5]
                        }
                    },
                    {
                        extend: 'csv',
                        title: 'LOGS ',
                        filename: 'LOGS',
                        text: 'Download CSV',
                        fieldSeparator: ',',
                        fieldBoundary: '"',
                        extension: '.csv',
                        exportOptions: {
                            columns: [0, 1, 2, 3, 4, 5]
                        },
                        bom: true,
                    },

                    {
                        extend: 'pdf',
                        title: 'LOGS',
                        filename: 'LOGS ',
                        orientation: 'portrait',
                        pageSize: 'letter',
                        text: 'Download PDF',
                        // messageTop: 'This report contains sales data.',
                        // messageBottom: 'Generated by My Application',
                        exportOptions: {
                            columns: [0, 1, 2, 3, 4, 5]
                        },
                        customize: function (doc) {
                            // Center-align all text
                            doc.defaultStyle.alignment = 'center';
                            
                            // Add custom margin to the second section (table data)
                            doc.content[1].margin = [0, 0, 25, 0];
                            
                            // Change table header style
                            doc.styles.tableHeader.fontSize = 12;
                            doc.styles.tableHeader.alignment = 'center';

                            if (doc.content[0] && doc.content[0].text) {
                                doc.content[0].fontSize = 12; // Set title font size
                                doc.content[0].bold = true;   // Set title to bold
                                doc.content[0].alignment = 'center';
                            }
                            
                            // Add header to the PDF
                            doc['header'] = function() {
                                return {
                                    text: 'LOGS REPORT',
                                    alignment: 'center',
                                    fontSize: 14,
                                    bold: true,
                                    margin: [0, 10]
                                }
                            };
                            var columnWidths = [70, 60, 100, 50, 150, 70]; // Adjust width for each column
                            doc.content[1].table.widths = columnWidths;
                        }
                    }

                ],
                pageLength: 10 // Adjust the number of entries per page
            });
        </script>
        <script>
            // Add the following code if you want the name of the file appear on select
            $(".custom-file-input").on("change", function() {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
            });

            $('input#coins').keyup(function(event) {
                // skip for arrow keys
                if(event.which >= 37 && event.which <= 40){
                event.preventDefault();
                }

                $(this).val(function(index, value) {
                    value = value.replace(/,/g,'');
                    return numberWithCommas(value);
                });
            });

            $('input#dc').keyup(function(event) {
                // skip for arrow keys
                if(event.which >= 37 && event.which <= 40){
                event.preventDefault();
                }

                $(this).val(function(index, value) {
                    value = value.replace(/,/g,'');
                    return numberWithCommas(value);
                });
            });

            $('input#pdc').keyup(function(event) {
                // skip for arrow keys
                if(event.which >= 37 && event.which <= 40){
                event.preventDefault();
                }

                $(this).val(function(index, value) {
                    value = value.replace(/,/g,'');
                    return numberWithCommas(value);
                });
            });

            $('input#totalremittance').keyup(function(event) {
                // skip for arrow keys
                if(event.which >= 37 && event.which <= 40){
                event.preventDefault();
                }

                $(this).val(function(index, value) {
                    value = value.replace(/,/g,'');
                    return numberWithCommas(value);
                });
            });

            $('input#amount').keyup(function(event) {
                // skip for arrow keys
                if(event.which >= 37 && event.which <= 40){
                event.preventDefault();
                }

                $(this).val(function(index, value) {
                    value = value.replace(/,/g,'');
                    return numberWithCommas(value);
                });
            });

            $('input#totalreturns').keyup(function(event) {
                // skip for arrow keys
                if(event.which >= 37 && event.which <= 40){
                event.preventDefault();
                }

                $(this).val(function(index, value) {
                    value = value.replace(/,/g,'');
                    return numberWithCommas(value);
                });
            });

            $('input#totalpalawan').keyup(function(event) {
                // skip for arrow keys
                if(event.which >= 37 && event.which <= 40){
                event.preventDefault();
                }

                $(this).val(function(index, value) {
                    value = value.replace(/,/g,'');
                    return numberWithCommas(value);
                });
            });


            

            $('input#totaltax').keyup(function(event) {
                // skip for arrow keys
                if(event.which >= 37 && event.which <= 40){
                event.preventDefault();
                }

                $(this).val(function(index, value) {
                    value = value.replace(/,/g,'');
                    return numberWithCommas(value);
                });
            });

            $('input#totalinc').keyup(function(event) {
                // skip for arrow keys
                if(event.which >= 37 && event.which <= 40){
                event.preventDefault();
                }

                $(this).val(function(index, value) {
                    value = value.replace(/,/g,'');
                    return numberWithCommas(value);
                });
            });

            $('input#totalbo').keyup(function(event) {
                // skip for arrow keys
                if(event.which >= 37 && event.which <= 40){
                event.preventDefault();
                }

                $(this).val(function(index, value) {
                    value = value.replace(/,/g,'');
                    return numberWithCommas(value);
                });
            });

            $('input#totalsrr').keyup(function(event) {
                // skip for arrow keys
                if(event.which >= 37 && event.which <= 40){
                event.preventDefault();
                }

                $(this).val(function(index, value) {
                    value = value.replace(/,/g,'');
                    return numberWithCommas(value);
                });
            });

            $('input#totalpalawanactual').keyup(function(event) {
                // skip for arrow keys
                if(event.which >= 37 && event.which <= 40){
                event.preventDefault();
                }

                $(this).val(function(index, value) {
                    value = value.replace(/,/g,'');
                    return numberWithCommas(value);
                });
            });

            //document.getElementById("btncustomer").focus();

            function numberWithCommas(x) {
                var parts = x.toString().split(".");
                parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, ",");
                return parts.join(".");
            }
        </script>
        <script src="<?php echo base_url(); ?>assets/js/dataTables.fixedColumns.min.js"></script>

        <script>
            $(function () {
                $("#ledger-date").datepicker({
                    dateFormat: "yy-mm-dd",
                    changeMonth: true,
                    changeYear: true,
                    showButtonPanel: true,
                    maxDate: 0
                });
            });

            let smTable;
            let previousDate = null; // global variable to track last selected date
            function formatReadableDate(dateString) {
                const options = { year: "numeric", month: "long", day: "numeric" };
                const date = new Date(dateString);
                return date.toLocaleDateString("en-US", options);
            }

            function updateHeaderDate(dateString) {
                const formattedDate = formatReadableDate(dateString);
                $("#display-date").text(formattedDate);
            }

            function loadTable(date) {
                // if ($.fn.DataTable.isDataTable('#cashier_sm_ledger')) {
                //     $('#cashier_sm_ledger').DataTable().clear().destroy();
                // }

                const tableId = '#cashier_sm_ledger';

                // If table exists, store current page
                let currentPage = 0;
                let isSameDate = (previousDate === date);

                if ($.fn.DataTable.isDataTable(tableId)) {
                    const existingTable = $(tableId).DataTable();
                    currentPage = existingTable.page();
                    existingTable.clear().destroy();
                }

                // Update the previousDate for future comparison
                previousDate = date;

                smTable = $('#cashier_sm_ledger').DataTable({
                    processing: true,
                    serverSide: true,
                    scrollX: true,
                    // stateSave: true,
                    fixedColumns: {
                        leftColumns: 4,
                        rightColumns: 4
                    },
                    ajax: {
                        url: "<?= site_url('get_cashier_sm_data_ajax') ?>",
                        type: "POST",
                        data: function (d) {
                            d.date = date; // send date to server
                        },

                        // beforeSend: function () {
                        // $('#cashier_sm_ledger tbody').html(`
                        //     <tr>
                        //         <td colspan="17" class="text-center">
                        //             <div style="padding: 30px 0;">
                        //                 <img src="<?= base_url('assets/img/loading.gif') ?>" alt="Loading..." style="height:100px;">
                        //                 <div style="margin-top: 10px; margin-bottom: 10px; font-weight: bold; color: #555;">Loading data, please wait...</div>
                        //             </div>
                        //         </td>
                        //     </tr>
                        // `);
                        // },
                        error: function (xhr, status, error) {
                            console.error("AJAX Error:", error);
                            $('#cashier_sm_ledger tbody').html(`
                                <tr>
                                    <td colspan="20" class="text-center text-danger">
                                        Failed to load data
                                    </td>
                                </tr>
                            `);
                        }
                    },

                    columns: [
                        { data: 'checkbox' },
                        { data: 'denom_id' },
                        { data: 'manualsrr' },
                        { data: 'salesman' },
                        { data: 'total_cash' },
                        { data: 'total_pal' },
                        { data: 'total_dc' },
                        { data: 'total_pdc' },
                        { data: 'total_collection' },
                        { data: 'coll_plus_pal' },
                        { data: 'remit_plus_pal' },
                        { data: 'satellite' },
                        { data: 'total_srr' },
                        { data: 'returns' },
                        { data: 'tax' },
                        { data: 'bo' },
                        { data: 'sm_inc' },
                        { data: 'rem_diff' },
                        { data: 'status' }, 
                        { data: 'actions' }
                    ],
                    columnDefs: [
                        {
                            targets: 1,
                            orderable: true
                        }
                    ],
                    order: [[1, 'asc']],
                    initComplete: function (settings, json) {
                        // Set to previous page if same date, otherwise go to first page
                        if (isSameDate && currentPage > 0) {
                            smTable.page(currentPage).draw(false);
                        } else {
                            smTable.page(0).draw(false); // Go to page 1
                        }
                    }
                });
            }


            
            $(document).ready(function () {
                const storedDate = localStorage.getItem("selectedLedgerDate");
                const today = storedDate || $("#ledger-date").val();

                $("#ledger-date").val(today);
                updateHeaderDate(today);
                loadTable(today);

                $("#ledger-date").on("change", function () {
                    const selectedDate = $(this).val();
                    localStorage.setItem("selectedLedgerDate", selectedDate);
                    updateHeaderDate(selectedDate);
                    loadTable(selectedDate);
                });
            });
        </script>

        <script>
            function loadTableSm() {
                if ($.fn.DataTable.isDataTable('#sm_denom_ledger')) {
                    $('#sm_denom_ledger').DataTable().clear().destroy();
                }

                $('#sm_denom_ledger').DataTable({
                    "processing": true,
                    "serverSide": true,
                    "stateSave": true,
                    "paging": true,
                    "searching": true,
                    "ordering": true,
                    "compact": true,
                    "ajax": {
                        "url": "<?= site_url('fetch_ledger_data') ?>",
                        "type": "POST"
                    },
                    "columns": [
                        { "data": "date_added" },
                        { "data": "manualsrr" },
                        { "data": "total_dc" },
                        { "data": "total_pdc" },
                        { "data": "total_cash" },
                        { "data": "total_palawan" },
                        { "data": "total_collection" },

                        <?php if ($this->session->userdata('location') != 'LDI' && $this->session->userdata('location') != 'LDI-CDC' && $this->session->userdata('location') != 'LDI-UDC') { ?>
                            { "data": "total_remittance" },
                        <?php } ?>

                        <?php if (in_array($this->session->userdata('location'), ['LDI', 'LDI-CDC', 'LDI-UDC'])) { ?>
                            { "data": "total_returns" },
                            // { "data": "vat_or_wtax" },
                            { "data": "bo" },
                        <?php } ?>

                        <?php if (in_array($this->session->userdata('bu'), ['XTRUCK', 'XTRUCK-NETMAN', 'XTRUCK-MPDI', 'XTRUCK-NETMAN-BPI'])) { ?>
                            { "data": "sm_inc" },
                        <?php } ?>

                        { "data": "status" },
                        { "data": "action", "orderable": false, "searchable": false }
                    ],
                    
                    "order": [[1, "asc"]]
                });
            }

            $(document).ready(function () {
                loadTableSm();
            });


        </script>

    </body>
</html>